pub const NVME_THROUGHPUT_BPS: u64 = 2_500_000_000;
pub const SATA_SSD_THROUGHPUT_BPS: u64 = 450_000_000;
pub const HDD_THROUGHPUT_BPS: u64 = 110_000_000;
pub const REMOVABLE_THROUGHPUT_BPS: u64 = 35_000_000;

pub const NVME_PER_FILE_MS: u64 = 2;
pub const SATA_SSD_PER_FILE_MS: u64 = 4;
pub const HDD_PER_FILE_MS: u64 = 15;
pub const REMOVABLE_PER_FILE_MS: u64 = 25;

pub const MOVE_SAME_VOLUME_PER_FILE_LOW_MS: u64 = NVME_PER_FILE_MS;
pub const MOVE_SAME_VOLUME_PER_FILE_HIGH_MS: u64 = HDD_PER_FILE_MS;

pub const COPY_THROUGHPUT_LOW_BPS: u64 = HDD_THROUGHPUT_BPS;
pub const COPY_THROUGHPUT_HIGH_BPS: u64 = SATA_SSD_THROUGHPUT_BPS;
pub const COPY_PER_FILE_LOW_MS: u64 = SATA_SSD_PER_FILE_MS;
pub const COPY_PER_FILE_HIGH_MS: u64 = HDD_PER_FILE_MS;

pub const CROSS_DEVICE_THROUGHPUT_LOW_BPS: u64 = REMOVABLE_THROUGHPUT_BPS;
pub const CROSS_DEVICE_THROUGHPUT_HIGH_BPS: u64 = HDD_THROUGHPUT_BPS;
pub const CROSS_DEVICE_PER_FILE_LOW_MS: u64 = HDD_PER_FILE_MS;
pub const CROSS_DEVICE_PER_FILE_HIGH_MS: u64 = REMOVABLE_PER_FILE_MS;

pub const SKIP_DUPLICATES_MULTIPLIER: f64 = 1.2;
